//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELaundry.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ELaundryDBEntities : DbContext
    {
        public ELaundryDBEntities()
            : base("name=ELaundryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBranch> tblBranches { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblClosing> tblClosings { get; set; }
        public virtual DbSet<tblGarment> tblGarments { get; set; }
        public virtual DbSet<tblInvoice> tblInvoices { get; set; }
        public virtual DbSet<tblOrder> tblOrders { get; set; }
        public virtual DbSet<tblOrderItem> tblOrderItems { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblSetting> tblSettings { get; set; }
        public virtual DbSet<tblTempOrder> tblTempOrders { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserBranch> tblUserBranches { get; set; }
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblSchedulePickup> tblSchedulePickups { get; set; }
        public virtual DbSet<tblTimeSlot> tblTimeSlots { get; set; }
    
        public virtual ObjectResult<getInvoiceByUserId_Date_Result> getInvoiceByUserId_Date()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getInvoiceByUserId_Date_Result>("getInvoiceByUserId_Date");
        }
    
        public virtual ObjectResult<GetTotalGarmentOrderCount_Result> GetTotalGarmentOrderCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTotalGarmentOrderCount_Result>("GetTotalGarmentOrderCount");
        }
    }
}
