//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELaundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClosing
    {
        public int ClosingId { get; set; }
        public Nullable<decimal> SalesAmount { get; set; }
        public Nullable<decimal> CashAmount { get; set; }
        public Nullable<System.DateTime> ClosingDateTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
