//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELaundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGarment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGarment()
        {
            this.tblOrderItems = new HashSet<tblOrderItem>();
            this.tblTempOrders = new HashSet<tblTempOrder>();
        }
    
        public int GarmentId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string GarmentName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderItem> tblOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTempOrder> tblTempOrders { get; set; }
    }
}
