//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELaundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderItem
    {
        public int OrderItemId { get; set; }
        public Nullable<int> GarmentId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string TakeAway { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual tblGarment tblGarment { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
