//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELaundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchedulePickup
    {
        public int id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string SecondaryAddress { get; set; }
        public string PickupDate { get; set; }
        public string DeliveryDate { get; set; }
        public string TimeSlot { get; set; }
        public Nullable<int> Userid { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
