//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELaundry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTempOrder
    {
        public int TempOrderId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string TokenNo { get; set; }
        public Nullable<int> GarmentId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> TW { get; set; }
        public string ItemState { get; set; }
    
        public virtual tblGarment tblGarment { get; set; }
    }
}
